// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQKfcuzhwsB5hdmcAtVCwlRMy06D9Iq8',
    appId: '1:572587422437:web:0160d5bcc338f6bc9f9a0c',
    messagingSenderId: '572587422437',
    projectId: 'election-75bfc',
    authDomain: 'election-75bfc.firebaseapp.com',
    databaseURL: 'https://election-75bfc-default-rtdb.firebaseio.com',
    storageBucket: 'election-75bfc.appspot.com',
    measurementId: 'G-52471D3ZV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLZFXfivU6Vp5o5H8uHcB0vao1X6hG64',
    appId: '1:572587422437:android:37970c9b073850669f9a0c',
    messagingSenderId: '572587422437',
    projectId: 'election-75bfc',
    databaseURL: 'https://election-75bfc-default-rtdb.firebaseio.com',
    storageBucket: 'election-75bfc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQKfcuzhwsB5hdmcAtVCwlRMy06D9Iq8',
    appId: '1:572587422437:web:a8af594511d8d5129f9a0c',
    messagingSenderId: '572587422437',
    projectId: 'election-75bfc',
    authDomain: 'election-75bfc.firebaseapp.com',
    databaseURL: 'https://election-75bfc-default-rtdb.firebaseio.com',
    storageBucket: 'election-75bfc.appspot.com',
    measurementId: 'G-S9TD4B6BNR',
  );
}
